name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use nightly version
        run: rustup override set nightly
          && rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --check
      - name: Linter
        run: cargo clippy -- -Dwarnings

  build:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v4
      - name: Use nightly version
        run: rustup override set nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Upload build artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-x86_64
          path: target/release/telegram-bot
      - name: Output artifact ID
        run: echo 'Artifact ID is ${{ steps.upload_artifact.outputs.artifact-id }}'
